### ISSUE TITLE
stop stealing sprites

### ISSUE THREAD

**Issue by AureusStratus** [Iron-Miner/ImprovedContent#1]
hey its not okay for you to be going this at least ask for permission if you can use the sprites

**Comment by Zeniku** [comment]
PLEASE STOP
You can always go to Mindustry modding server
We can help you not steal

![Screenshot_2021-04-17-15-17-00-84](https://user-images.githubusercontent.com/65060027/115105332-ddc95b80-9f90-11eb-9357-ef822b3221e1.jpg)
![Screenshot_2021-04-17-15-16-04-88](https://user-images.githubusercontent.com/65060027/115105343-e91c8700-9f90-11eb-9298-73f65098509b.jpg)
For contex this is from MechanicalWarfare v5 mindustry mod

**Comment by EmanuelG-Gaming** [comment]
> hey its not okay for you to be going this at least ask for permission if you can use the sprites

Yes, absolutely true...
