### ISSUE TITLE
License break

### ISSUE THREAD

**Issue by GlennFolker** [Iron-Miner/ImprovedContent#3]
According to the GNU GPL v3.0 *(which is used in [`mechanical-warfare`](https://github.com/JerichoFletcher/mechanical-warfare))*:
> ## Quick Summary
> You may copy, distribute and modify the software as long as you track changes/dates in source files. Any modifications to or software including (via compiler) GPL-licensed code must also be made available under the GPL along with build & install instructions.

You stole [a sprite](https://github.com/Iron-Miner/ImprovedContent/blob/main/sprites/blocks/riptide.png) without addressing their owners nor did you credit them anywhere. Yes I know that you edited it but I can see through your lies; for God's sake I made [the sprite](https://github.com/JerichoFletcher/mechanical-warfare/blob/master/sprites/mechs/ships/halberd-ship.png) and I know exactly every pixel I drew there. Also, according to your older commits, it was a direct [copy-paste](https://github.com/Iron-Miner/ImprovedContent/blob/33e99b6d1157a8acd3a10eb50d3723aebcdae685/sprites/blocks/riptide.png) *(from the [33e99b6d1157a8acd3a10eb50d3723aebcdae685] commit node)*.

These actions cannot be tolerated and will risk this repository to be taken down, so I require you to take the sprite and other stolen contents down and go start making your own.

**Comment by AzhurniyBaklan** [comment]
https://www.gnu.org/licenses/gpl-3.0.en.html if you wish to read more about the right you've just broken

**Comment by Iron-Miner** [comment]
ok i will give you the credit for the sprite
